version: '3.2'
name: php3_v33
services:
  apache:
    container_name: apache_prac3_v2_php_1
    build: ./apache
    ports:
      - "80:80"
    volumes:
      - ./apache:/var/www/html
      - ./apache/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db_pr3_v2
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=alla
    networks:
      - net1
  db:
    build: ./mysql
    ports:
      - "3308:3308"
    container_name: db_pr3_php
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - net1


networks:
  net1: